In [6]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

### preprocessing data

In [7]:
data = pd.read_csv("./Fish.csv").set_axis([i for i in range(7)], axis=1)
# converting the categorical data into numericals
one_hot = pd.get_dummies(data[0])
raw_data = data.drop(0, axis=1)
data = raw_data.join(one_hot)

# Normalizing the data
cols = [i for i in range(1,7)]
min_max_scaler = MinMaxScaler()
x = data[cols].values
x_scaled = min_max_scaler.fit_transform(x)

normalized = pd.DataFrame(x_scaled, columns=cols, index=data.index)
data[cols] = normalized
data

,1,2,3,4,5,6,Bream,Parkki,Perch,Pike,Roach,Smelt,Whitefish
0,0.146667,0.304854,0.309091,0.358108,0.568334,0.418978,True,False,False,False,False,False,False
1,0.175758,0.320388,0.325455,0.378378,0.624055,0.459235,True,False,False,False,False,False,False
2,0.206061,0.318447,0.329091,0.376689,0.618123,0.514279,True,False,False,False,False,False,False
3,0.220000,0.365049,0.374545,0.417230,0.638566,0.480365,True,False,False,False,False,False,False
4,0.260606,0.368932,0.374545,0.425676,0.621966,0.576004,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
154,0.007394,0.077670,0.069091,0.077703,0.021012,0.048771,False,False,False,False,False,True,False
155,0.008121,0.081553,0.072727,0.079392,0.040723,0.031208,False,False,False,False,False,True,False
156,0.007394,0.089320,0.083636,0.084459,0.031842,0.029347,False,False,False,False,False,True,False
157,0.011939,0.110680,0.107273,0.108108,0.066424,0.143719,False,False,False,False,False,True,False
158,0.012061,0.122330,0.120000,0.125000,0.069872,0.117219,False,False,False,False,False,True,False

### Choosing Target variable and Spliting the dataset

In [8]:
Y = np.array(data.pop(1))
X = np.array(data)

print(X.shape, Y.shape)

X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=.2)
print(X_test.shape, Y_test.shape)

(159, 12) (159,)
(32, 12) (32,)

### Init and Training the Regression Model

In [9]:
from sklearn.linear_model import LinearRegression

In [ ]:
# using linear algebra (normal equation and inverse/pesudo inverse)
lr = LinearRegression()
lr.fit(X_train, Y_train)

score = lr.score(X_test, Y_test)
print(score)

sampls_5_x = X_test[:5,:]
sampls_5_y = Y_test[:5]

print(sampls_5_y, lr.predict(sampls_5_x), sep="\n")

0.9116922634093608
[0.10242424 0.01193939 0.59090909 0.26060606 0.60606061]
[0.1953125 0.0703125 0.6015625 0.21875   0.6171875]